#! /bin/env python
# -*- coding: utf-8 -*-
import re
import sys
from bxh.command_line import extractdiffdirs
if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(extractdiffdirs())
