---
title: "Linear Models with AD and MCI"
author: "Anna MacFarlane & Alex Badea"
date: "9/9/2021"
output: pdf_document
---

Note: blue stars on upper plots denote subject with AD, and green squares
indicate subjects with MCI

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE, echo = FALSE)
#tinytex::install_tinytex()
library(tidyverse)
library(cowplot)
data <- read.csv("AD_DECODE_data.csv")

#ad_pat <- which(data$risk_for_ad == 2)

ad <- data %>% 
  #filter(! is.na(Weight)) %>% 
  mutate(sex = case_when(
    sex == "F" ~ "Female",
    sex == "M" ~ "Male"
  )) %>% 
  filter(risk_for_ad != 3) %>% 
  filter(risk_for_ad != 2)

# data by genotypes
e23 <- ad %>% 
  filter(genotype == "APOE23") 
e33 <- ad %>% 
  filter(genotype == "APOE33")
e34 <- ad %>% 
  filter(genotype == "APOE34")

# combining genotypes 
geno_combined <- ad %>% 
  mutate(genotype = case_when(
    genotype == "APOE23" | genotype == "APOE33" ~ "APOE3",
    genotype == "APOE34" | genotype == "APOE44" ~ "APOE4"
  )) 

# separating by sex
combo_f <- geno_combined %>% 
  filter(sex == "Female")

combo_m <- geno_combined %>% 
  filter(sex == "Male")

f_facet <- data %>% 
  filter(risk_for_ad == 3 | risk_for_ad == 2)  %>% 
  filter(sex == "Female")

m_facet <- data %>% 
  filter(risk_for_ad == 3 | risk_for_ad == 2)  %>% 
  filter(sex == "Male")
  
  

MCI <- data %>% 
  filter(risk_for_ad == "2") %>%
mutate(genotype = case_when(
    genotype == "APOE23" | genotype == "APOE33" ~ "APOE3",
    genotype == "APOE34" | genotype == "APOE44" ~ "APOE4"
  )) 

AD <- data %>% 
  filter(risk_for_ad == "3") %>%
mutate(genotype = case_when(
    genotype == "APOE23" | genotype == "APOE33" ~ "APOE3",
    genotype == "APOE34" | genotype == "APOE44" ~ "APOE4"
  ))

MCI_m <- MCI %>% 
  filter(sex == "M")

MCI_f <- MCI %>% 
  filter(sex == "F")

AD_m <- AD %>% 
  filter(sex == "M")

AD_f <- AD %>% 
  filter(sex == "F")
```

``` {r ufov-1, echo = FALSE}
plot1<-ggplot(geno_combined, aes(x = age, y = ufov1, color = genotype,  fill = genotype))+
  geom_point(aes(shape = Risk,pch = 4,color = genotype,  fill = genotype)) +
  geom_smooth(formula = y ~ x, method = "lm", alpha = 0.2) +
  labs(title = "UFOV1 scores linear model",
       subtitle = "Both males and females",
       x = "Age", y = "UFOV1 score") + 
  theme_bw() +
  background_grid(major = "xy", minor = "none") +
 annotate("point", x = MCI$age, y = MCI$ufov1, colour = "darkgreen", shape = 15, cex=3) +
  annotate("point", x = AD$age, y = AD$ufov1, colour = "purple2", pch=17, shape = 17, cex=3) +
  xlim(20,90)

plot2 <- ggplot(combo_f, aes(age, ufov1, 
                                   color = genotype, fill = genotype)) + 
  geom_point(aes(shape = Risk)) + 
  annotate("point", x = MCI_f$age, y = MCI_f$ufov1, colour = "darkgreen", shape = 9, cex=3) +
  annotate("point", x = AD_f$age, y = AD_f$ufov1, colour = "purple2", shape = 8, cex=3) +
  stat_smooth(method = "lm", alpha = 0.2) +
  background_grid(major = 'xy', minor = "none") + # add thin horizontal lines 
  panel_border() + 
  theme_bw()+
  labs(x = "Age", y = "UFOV1 score", title = "Female") +
  theme(legend.position="none") +
    xlim(20,90)




plot3 <- ggplot(combo_m, aes(age, ufov1, 
                                   color = genotype, fill = genotype)) + 
  geom_point(aes(shape = Risk)) + 
  stat_smooth(method = "lm", alpha = 0.2) +
  background_grid(major = 'xy', minor = "none") + # add thin horizontal lines 
  panel_border() + 
  theme_bw()+
  labs(x = "Age", title = "Male") +
  theme(legend.position="none", axis.ticks.y=element_blank(), axis.title.y=element_blank(),
        axis.text.y=element_blank()) +
  annotate("point", x = MCI_m$age, y = MCI_m$ufov1, colour = "darkgreen", shape = 9, cex=3) +
  annotate("point", x = AD_m$age, y = AD_m$ufov1, colour = "purple2", shape = 8, cex=3) +
  xlim(20,90)

#geom_point(data=MCI,pch = 8, cex=20)

ggdraw() + 
  draw_plot(plot1, 0, .5, 1, .5) +
  draw_plot(plot2, 0, 0, 0.5, .5) +
  draw_plot(plot3, 0.5, 0, .45, .5)

lm <- lm(ufov1 ~ age*genotype*sex, geno_combined)
summary(lm)

lm_f <- lm(ufov1 ~ age*genotype, combo_f)
summary(lm_f)

lm_m <- lm(ufov1 ~ age*genotype, combo_m)
summary(lm_m)

anova(lm)
anova(lm_f)
anova(lm_m)
```

```{r ufov-2, echo = FALSE}
plot1<-ggplot(geno_combined, aes(x = age, y = ufov2,
                                 color = genotype,  fill = genotype)) + 
  geom_point(aes(shape = Risk)) +
  geom_smooth(formula = y ~ x, method = "lm", alpha = 0.2) +
  labs(title = "UFOV2 scores linear model",
       subtitle = "Both males and females",
       x = "Age", y = "UFOV2 score") +
  theme_bw() +
  background_grid(major = "xy", minor = "none") +
  annotate("point", x = MCI$age, y = MCI$ufov2, colour = "darkgreen", shape = 15, cex=3) +
  annotate("point", x = AD$age, y = AD$ufov2, colour = "purple2", pch=17, shape = 17, cex=3) +
  xlim(20,90)

plot2 <- ggplot(combo_f, aes(age, ufov2, 
                                   color = genotype, fill = genotype)) + 
  geom_point(aes(shape = Risk)) + 
  stat_smooth(method = "lm", alpha = 0.2) +
  background_grid(major = 'xy', minor = "none") + # add thin horizontal lines 
  panel_border() + 
  theme_bw()+
  labs(x = "Age", y = "UFOV2 score", title = "Female") +
  theme(legend.position="none") +
  annotate("point", x = MCI_f$age, y = MCI_f$ufov2, colour = "darkgreen", shape = 15, cex=3) +
  annotate("point", x = AD_f$age, y = AD_f$ufov2, colour = "purple2", pch=17, shape = 17, cex=3)+
 xlim(20,90)


plot3 <- ggplot(combo_m, aes(age, ufov2, 
                                   color = genotype, fill = genotype)) + 
  geom_point(aes(shape = Risk)) + 
  stat_smooth(method = "lm", alpha = 0.2) +
  background_grid(major = 'xy', minor = "none") + # add thin horizontal lines 
  panel_border() + 
  theme_bw()+
  labs(x = "Age", title = "Male") +
  theme(legend.position="none", axis.ticks.y=element_blank(), axis.title.y=element_blank(),
        axis.text.y=element_blank()) +
  annotate("point", x = MCI_m$age, y = MCI_m$ufov2, colour = "darkgreen", shape = 15, cex=3) +
  annotate("point", x = AD_m$age, y = AD_m$ufov2, colour = "purple2", pch=17, shape = 17, cex=3)+
xlim(20,90)

ggdraw() + 
  draw_plot(plot1, 0, .5, 1, .5) +
  draw_plot(plot2, 0, 0, 0.5, .5) +
  draw_plot(plot3, 0.5, 0, .45, .5)

lm <- lm(ufov2 ~ age*genotype*sex, geno_combined)
summary(lm)

lm_f <- lm(ufov2 ~ age*genotype, combo_f)
summary(lm_f)

lm_m <- lm(ufov2 ~ age*genotype, combo_m)
summary(lm_m)

anova(lm)
anova(lm_f)
anova(lm_m)

```


```{r ufov-3, echo = FALSE}
plot1<-ggplot(geno_combined, aes(x = age, y = ufov3,
                                 color = genotype,  fill = genotype)) + 
  geom_point(aes(shape = Risk)) +
  geom_smooth(formula = y ~ x, method = "lm", alpha = 0.2) +
  labs(title = "UFOV3 scores linear model",
       subtitle = "Both males and females",
       x = "Age", y = "UFOV3 score") +
  theme_bw() +
  background_grid(major = "xy", minor = "none") +
  annotate("point", x = MCI$age, y = MCI$ufov3, colour = "darkgreen", shape = 15, cex=3) +
  annotate("point", x = AD$age, y = AD$ufov3, colour = "purple2", pch=17, shape = 17, cex=3)+
  xlim(20,90)

plot2 <- ggplot(combo_f, aes(age, ufov3, color = genotype, fill = genotype)) + 
  geom_point(aes(shape = Risk)) + 
  stat_smooth(method = "lm", alpha = 0.2) +
  background_grid(major = 'xy', minor = "none") + # add thin horizontal lines 
  panel_border() + 
  theme_bw()+
  labs(x = "Age", y = "UFOV3 score", title = "Female") +
  theme(legend.position="none") +
  annotate("point", x = MCI_f$age, y = MCI_f$ufov3, colour = "darkgreen", shape = 15, cex=3) +
  annotate("point", x = AD_f$age, y = AD_f$ufov3, colour = "purple2", pch=17, shape = 17, cex=3)+
  xlim(20,90)

plot3 <- ggplot(combo_m, aes(age, ufov3, 
                                   color = genotype, fill = genotype)) + 
  geom_point(aes(shape = Risk)) + 
  stat_smooth(method = "lm", alpha = 0.2) +
  background_grid(major = 'xy', minor = "none") + # add thin horizontal lines 
  panel_border() + 
  theme_bw()+
  labs(x = "Age", title = "Male") +
  theme(legend.position="none", axis.ticks.y=element_blank(), axis.title.y=element_blank(),
        axis.text.y=element_blank()) +
  annotate("point", x = MCI_m$age, y = MCI_m$ufov2, colour = "darkgreen", shape = 15, cex=3) +
  annotate("point", x = AD_m$age, y = AD_m$ufov2, colour = "purple2", pch=17, shape = 17, cex=3)+
  xlim(20,90)

ggdraw() + 
  draw_plot(plot1, 0, .5, 1, .5) +
  draw_plot(plot2, 0, 0, 0.5, .5) +
  draw_plot(plot3, 0.5, 0, .45, .5)

lm <- lm(ufov3 ~ age*genotype*sex, geno_combined)
summary(lm)

lm_f <- lm(ufov3 ~ age*genotype, combo_f)
summary(lm_f)

lm_m <- lm(ufov3 ~ age*genotype, combo_m)
summary(lm_f)

anova(lm)
anova(lm_f)
anova(lm_m)

```


```{r animals-norepeats, echo = FALSE}

plot1<-ggplot(geno_combined, aes(x = age, y = animals,
                                 color = genotype,  fill = genotype)) + 
  geom_point(aes(shape = Risk)) +
  geom_smooth(formula = y ~ x, method = "lm", alpha = 0.2) +
  labs(title = "Animal naming scores linear model",
       subtitle = "Both males and females",
       x = "Age", y = "Animal naming score") +
  theme_bw() +
  background_grid(major = "xy", minor = "none") +
  annotate("point", x = MCI$age, y = MCI$animals, colour = "darkgreen", shape = 15, cex=3) +
  annotate("point", x = AD$age, y = AD$animals, colour = "purple2", pch=17, shape = 17, cex=3)+
  xlim(20,90)

plot2 <- ggplot(combo_f, aes(age, animals, 
                                   color = genotype, fill = genotype)) + 
  geom_point(aes(shape = Risk)) + 
  stat_smooth(method = "lm", alpha = 0.2) +
  background_grid(major = 'xy', minor = "none") + # add thin horizontal lines 
  panel_border() + 
  theme_bw()+
  labs(x = "Age", y = "Animal naming score", title = "Female") +
  theme(legend.position="none") +
  annotate("point", x = MCI_f$age, y = MCI_f$animals, colour = "darkgreen", shape = 15, cex=3) +
  annotate("point", x = AD_f$age, y = AD_f$animals, colour = "purple2", pch=17, shape = 17, cex=3)+
  xlim(20,90)

plot3 <- ggplot(combo_m, aes(age, animals, 
                                   color = genotype, fill = genotype)) + 
  geom_point(aes(shape = Risk)) + 
  stat_smooth(method = "lm", alpha = 0.2) +
  background_grid(major = 'xy', minor = "none") + # add thin horizontal lines 
  panel_border() + 
  theme_bw()+
  labs(x = "Age", title = "Male") +
  theme(legend.position="none", axis.ticks.y=element_blank(), axis.title.y=element_blank(),
        axis.text.y=element_blank()) +
  annotate("point", x = MCI_m$age, y = MCI_m$animals, colour = "darkgreen", shape = 15, cex=3) +
  annotate("point", x = AD_m$age, y = AD_m$animals, colour = "purple2", pch=17, shape = 17, cex=3)+
  xlim(20,90)

ggdraw() + 
  draw_plot(plot1, 0, .5, 1, .5) +
  draw_plot(plot2, 0, 0, 0.5, .5) +
  draw_plot(plot3, 0.5, 0, .45, .5)

lm <- lm(animals ~ age*genotype*sex, geno_combined)
summary(lm)

lm_f <- lm(animals ~ age*genotype, combo_f)
summary(lm_f)

lm_m <- lm(animals ~ age*genotype, combo_m)
summary(lm_m)

anova(lm)
anova(lm_f)
anova(lm_m)


```


```{r vegetables-norepeats, echo = FALSE}

plot1<-ggplot(geno_combined, aes(x = age, y = vegetables,
                                 color = genotype,  fill = genotype)) + 
  geom_point(aes(shape = Risk)) +
  geom_smooth(formula = y ~ x, method = "lm", alpha = 0.2) +
  labs(title = "Vegetable naming scores linear model",
       subtitle = "Both males and females",
       x = "Age", y = "Vegetable naming score") +
  theme_bw() +
  background_grid(major = "xy", minor = "none") +
  annotate("point", x = MCI$age, y = MCI$vegetables, colour = "darkgreen", shape = 15, cex=3) +
  annotate("point", x = AD$age, y = AD$vegetables, colour = "purple2", pch=17, shape = 17, cex=3)+
  xlim(20,90)

plot2 <- ggplot(combo_f, aes(age, vegetables, 
                                   color = genotype, fill = genotype)) + 
  geom_point(aes(shape = Risk)) + 
  stat_smooth(method = "lm", alpha = 0.2) +
  background_grid(major = 'xy', minor = "none") + # add thin horizontal lines 
  panel_border() + 
  theme_bw()+
  labs(x = "Age", y = "Vegetable naming score", title = "Female") +
  theme(legend.position="none") +
  annotate("point", x = MCI_f$age, y = MCI_f$vegetables, colour = "darkgreen", shape = 15, cex=3) +
  annotate("point", x = AD_f$age, y = AD_f$vegetables, colour = "purple2", pch=17, shape = 17, cex=3)+
  xlim(20,90)

plot3 <- ggplot(combo_m, aes(age, vegetables, 
                                   color = genotype, fill = genotype)) + 
  geom_point(aes(shape = Risk)) + 
  stat_smooth(method = "lm", alpha = 0.2) +
  background_grid(major = 'xy', minor = "none") + # add thin horizontal lines 
  panel_border() + 
  theme_bw()+
  labs(x = "Age", title = "Male") +
  theme(legend.position="none", axis.ticks.y=element_blank(), axis.title.y=element_blank(),
        axis.text.y=element_blank()) +
  annotate("point", x = MCI_m$age, y = MCI_m$vegetables, colour = "darkgreen", shape = 15, cex=3) +
  annotate("point", x = AD_m$age, y = AD_m$vegetables, colour = "purple2", pch=17, shape = 17, cex=3)+
  xlim(20,90)

ggdraw() + 
  draw_plot(plot1, 0, .5, 1, .5) +
  draw_plot(plot2, 0, 0, 0.5, .5) +
  draw_plot(plot3, 0.5, 0, .45, .5)

lm <- lm(vegetables ~ age*genotype*sex, geno_combined)
summary(lm)

lm_f <- lm(vegetables ~ age*genotype, combo_f)
summary(lm_f)

lm_m <- lm(vegetables ~ age*genotype, combo_m)
summary(lm_m)

anova(lm)
anova(lm_f)
anova(lm_m)
```

```{r f-norepeats, echo = FALSE}
plot1<-ggplot(geno_combined, aes(x = age, y = f,
                                 color = genotype,  fill = genotype)) + 
  geom_point(aes(shape = Risk)) +
  geom_smooth(formula = y ~ x, method = "lm", alpha = 0.2) +
  labs(title = "F words naming scores linear model",
       subtitle = "Both males and females",
       x = "Age", y = "F words naming score") +
  theme_bw() +
  background_grid(major = "xy", minor = "none") +
  annotate("point", x = MCI$age, y = MCI$f, colour = "darkgreen", shape = 15, cex=3) +
  annotate("point", x = AD$age, y = AD$f, colour = "purple2", pch=17, shape = 17, cex=3)+
  xlim(20,90)

plot2 <- ggplot(combo_f, aes(age, f, 
                                   color = genotype, fill = genotype)) + 
  geom_point(aes(shape = Risk)) + 
  stat_smooth(method = "lm", alpha = 0.2) +
  background_grid(major = 'xy', minor = "none") + # add thin horizontal lines 
  panel_border() + 
  theme_bw()+
  labs(x = "Age", y = "F words naming score", title = "Female") +
  theme(legend.position="none") +
  annotate("point", x = MCI_f$age, y = MCI_f$f, colour = "darkgreen", shape = 15, cex=3) +
  annotate("point", x = AD_f$age, y = AD_f$f, colour = "purple2", pch=17, shape = 17, cex=3)+
  xlim(20,90)

plot3 <- ggplot(combo_m, aes(age, f, 
                                   color = genotype, fill = genotype)) + 
  geom_point(aes(shape = Risk)) + 
  stat_smooth(method = "lm", alpha = 0.2) +
  background_grid(major = 'xy', minor = "none") + # add thin horizontal lines 
  panel_border() + 
  theme_bw()+
  labs(x = "Age", title = "Male") +
  theme(legend.position="none", axis.ticks.y=element_blank(), axis.title.y=element_blank(),
        axis.text.y=element_blank()) +
  annotate("point", x = MCI_m$age, y = MCI_m$f, colour = "darkgreen", shape = 15, cex=3) +
  annotate("point", x = AD_m$age, y = AD_m$f, colour = "purple2", pch=17, shape = 17, cex=3)+
  xlim(20,90)

ggdraw() + 
  draw_plot(plot1, 0, .5, 1, .5) +
  draw_plot(plot2, 0, 0, 0.5, .5) +
  draw_plot(plot3, 0.5, 0, .45, .5)

lm <- lm(f ~ age*genotype*sex, geno_combined)
summary(lm)

lm_f <- lm(f ~ age*genotype, combo_f)
summary(lm_f)

lm_m <- lm(f ~ age*genotype, combo_m)
summary(lm_m)

anova(lm)
anova(lm_f)
anova(lm_m)

```




```{r l-norepeats, echo = FALSE}

plot1<-ggplot(geno_combined, aes(x = age, y = l,
                                 color = genotype,  fill = genotype)) + 
  geom_point(aes(shape = Risk)) +
  geom_smooth(formula = y ~ x, method = "lm", alpha = 0.2) +
  labs(title = "L words naming scores linear model",
       subtitle = "Both males and females",
       x = "Age", y = "L words naming score") +
  theme_bw() +
  background_grid(major = "xy", minor = "none") +
  annotate("point", x = MCI$age, y = MCI$l, colour = "darkgreen", shape = 15, cex=3) +
  annotate("point", x = AD$age, y = AD$l, colour = "purple2", pch=17, shape = 17, cex=3)+
  xlim(20,90)


plot2 <- ggplot(combo_f, aes(age, l, 
                                   color = genotype, fill = genotype)) + 
  geom_point(aes(shape = Risk)) + 
  stat_smooth(method = "lm", alpha = 0.2) +
  background_grid(major = 'xy', minor = "none") + # add thin horizontal lines 
  panel_border() + 
  theme_bw()+
  labs(x = "Age", y = "L words naming score", title = "Female") +
  theme(legend.position="none") +
  annotate("point", x = MCI_f$age, y = MCI_f$l, colour = "darkgreen", shape = 15, cex=3) +
  annotate("point", x = AD_f$age, y = AD_f$l, colour = "purple2", pch=17, shape = 17, cex=3)+
  xlim(20,90)

plot3 <- ggplot(combo_m, aes(age, l, 
                                   color = genotype, fill = genotype)) + 
  geom_point(aes(shape = Risk)) + 
  stat_smooth(method = "lm", alpha = 0.2) +
  background_grid(major = 'xy', minor = "none") + # add thin horizontal lines 
  panel_border() + 
  theme_bw()+
  labs(x = "Age", title = "Male") +
  theme(legend.position="none", axis.ticks.y=element_blank(), axis.title.y=element_blank(),
        axis.text.y=element_blank()) +
  annotate("point", x = MCI_m$age, y = MCI_m$l, colour = "darkgreen", shape = 15, cex=3) +
  annotate("point", x = AD_m$age, y = AD_m$l, colour = "purple2", pch=17, shape = 17, cex=3)+
  xlim(20,90)

ggdraw() + 
  draw_plot(plot1, 0, .5, 1, .5) +
  draw_plot(plot2, 0, 0, 0.5, .5) +
  draw_plot(plot3, 0.5, 0, .45, .5)

lm <- lm(l ~ age*genotype*sex, geno_combined)
summary(lm)

lm_f <- lm(l ~ age*genotype, combo_f)
summary(lm_f)

lm_m <- lm(l ~ age*genotype, combo_m)
summary(lm_m)

anova(lm)
anova(lm_f)
anova(lm_m)
```



```{r trail-A, echo = FALSE}

plot1<-ggplot(geno_combined, aes(x = age, y = trailA,
                                 color = genotype,  fill = genotype)) + 
  geom_point(aes(shape = Risk)) +
  geom_smooth(formula = y ~ x, method = "lm", alpha = 0.2) +
  labs(title = "Trail A scores linear model",
       subtitle = "Both males and females",
       x = "Age", y = "Trail A score") +
  theme_bw() +
  background_grid(major = "xy", minor = "none") +
  annotate("point", x = MCI$age, y = MCI$trailA, colour = "darkgreen", shape = 15, cex=3) +
  annotate("point", x = AD$age, y = AD$trailA, colour = "purple2", pch=17, shape = 17, cex=3)+
  xlim(20,90)

plot2 <- ggplot(combo_f, aes(age, trailA, 
                                   color = genotype, fill = genotype)) + 
  geom_point(aes(shape = Risk)) + 
  stat_smooth(method = "lm", alpha = 0.2) +
  background_grid(major = 'xy', minor = "none") + # add thin horizontal lines 
  panel_border() + 
  theme_bw()+
  labs(x = "Age", y = "Trail A score", title = "Female") +
  theme(legend.position="none") +
  annotate("point", x = MCI_f$age, y = MCI_f$trailA, colour = "darkgreen", shape = 15, cex=3) +
  annotate("point", x = AD_f$age, y = AD_f$trailA, colour = "purple2", pch=17, shape = 17, cex=3)+
  xlim(20,90)

plot3 <- ggplot(combo_m, aes(age, trailA, 
                                   color = genotype, fill = genotype)) + 
  geom_point(aes(shape = Risk)) + 
  stat_smooth(method = "lm", alpha = 0.2) +
  background_grid(major = 'xy', minor = "none") + # add thin horizontal lines 
  panel_border() + 
  theme_bw()+
  labs(x = "Age", title = "Male") +
  theme(legend.position="none", axis.ticks.y=element_blank(), axis.title.y=element_blank(),
        axis.text.y=element_blank()) +
  annotate("point", x = MCI_m$age, y = MCI_m$trailA, colour = "darkgreen", shape = 15, cex=3) +
  annotate("point", x = AD_m$age, y = AD_m$trailA, colour = "purple2", pch=17, shape = 17, cex=3)+
  xlim(20,90)

ggdraw() + 
  draw_plot(plot1, 0, .5, 1, .5) +
  draw_plot(plot2, 0, 0, 0.5, .5) +
  draw_plot(plot3, 0.5, 0, .45, .5)

lm <- lm(trailA ~ age*genotype*sex, geno_combined)
summary(lm)

lm_f <- lm(trailA ~ age*genotype, combo_f)
summary(lm_f)

lm_m <- lm(trailA ~ age*genotype, combo_m)
summary(lm_m)

anova(lm)
anova(lm_f)
anova(lm_m)
```


```{r trail-B, echo = FALSE}

plot1<-ggplot(geno_combined, aes(x = age, y = trailB,
                                 color = genotype,  fill = genotype)) + 
  geom_point(aes(shape = Risk)) +
  geom_smooth(formula = y ~ x, method = "lm", alpha = 0.2) +
  labs(title = "Trail B scores linear model",
       subtitle = "Both males and females",
       x = "Age", y = "Trail B score") +
  theme_bw() +
  background_grid(major = "xy", minor = "none") +
  annotate("point", x = MCI$age, y = MCI$trailB, colour = "darkgreen", shape = 15, cex=3) +
  annotate("point", x = AD$age, y = AD$trailB, colour = "purple2", pch=17, shape = 17, cex=3)+
  xlim(20,90)

plot2 <- ggplot(combo_f, aes(age, trailB, 
                                   color = genotype, fill = genotype)) + 
  geom_point(aes(shape = Risk)) + 
  stat_smooth(method = "lm", alpha = 0.2) +
  background_grid(major = 'xy', minor = "none") + # add thin horizontal lines 
  panel_border() + 
  theme_bw()+
  labs(x = "Age", y = "Trail B score", title = "Female") +
  theme(legend.position="none") +
  annotate("point", x = MCI_f$age, y = MCI_f$trailB, colour = "darkgreen", shape = 15, cex=3) +
  annotate("point", x = AD_f$age, y = AD_f$trailB, colour = "purple2", pch=17, shape = 17, cex=3)+
  xlim(20,90)

plot3 <- ggplot(combo_m, aes(age, trailB, 
                                   color = genotype, fill = genotype)) + 
  geom_point(aes(shape = Risk)) + 
  stat_smooth(method = "lm", alpha = 0.2) +
  background_grid(major = 'xy', minor = "none") + # add thin horizontal lines 
  panel_border() + 
  theme_bw()+
  labs(x = "Age", title = "Male") +
  theme(legend.position="none", axis.ticks.y=element_blank(), axis.title.y=element_blank(),
        axis.text.y=element_blank()) +
  annotate("point", x = MCI_m$age, y = MCI_m$trailB, colour = "darkgreen", shape = 15, cex=3) +
  annotate("point", x = AD_m$age, y = AD_m$trailB, colour = "purple2", pch=17, shape = 17, cex=3)+
  xlim(20,90)

ggdraw() + 
  draw_plot(plot1, 0, .5, 1, .5) +
  draw_plot(plot2, 0, 0, 0.5, .5) +
  draw_plot(plot3, 0.5, 0, .45, .5)

lm <- lm(trailB ~ age*genotype*sex, geno_combined)
summary(lm)

lm_f <- lm(trailB ~ age*genotype, combo_f)
summary(lm_f)

lm_m <- lm(trailB ~ age*genotype, combo_m)
summary(lm_m)

anova(lm)
anova(lm_f)
anova(lm_m)
```


```{r trail-differ, echo = FALSE}

plot1<-ggplot(geno_combined, aes(x = age, y = trailDiff,
                                 color = genotype,  fill = genotype)) + 
  geom_point(aes(shape = Risk)) +
  geom_smooth(formula = y ~ x, method = "lm", alpha = 0.2) +
  labs(title = "Difference between trail scores linear model",
       subtitle = "Both males and females",
       x = "Age", y = "Trail scores difference") +
  theme_bw() +
  background_grid(major = "xy", minor = "none") +
  annotate("point", x = MCI$age, y = MCI$trailDiff, colour = "darkgreen", shape = 15, cex=3) +
  annotate("point", x = AD$age, y = AD$trailDiff, colour = "purple2", pch=17, shape = 17, cex=3)+
  xlim(20,90)

plot2 <- ggplot(combo_f, aes(age, trailDiff, 
                                   color = genotype, fill = genotype)) + 
  geom_point(aes(shape = Risk)) + 
  stat_smooth(method = "lm", alpha = 0.2) +
  background_grid(major = 'xy', minor = "none") + # add thin horizontal lines 
  panel_border() + 
  theme_bw()+
  labs(x = "Age", y = "Trail scores difference", title = "Female") +
  theme(legend.position="none") +
  annotate("point", x = MCI_f$age, y = MCI_f$trailDiff, colour = "darkgreen", shape = 15, cex=3) +
  annotate("point", x = AD_f$age, y = AD_f$trailDiff, colour = "purple2", pch=17, shape = 17, cex=3)+
  xlim(20,90)

plot3 <- ggplot(combo_m, aes(age, trailDiff, 
                                   color = genotype, fill = genotype)) + 
  geom_point(aes(shape = Risk)) + 
  stat_smooth(method = "lm", alpha = 0.2) +
  background_grid(major = 'xy', minor = "none") + # add thin horizontal lines 
  panel_border() + 
  theme_bw()+
  labs(x = "Age", title = "Male") +
  theme(legend.position="none", axis.ticks.y=element_blank(), axis.title.y=element_blank(),
        axis.text.y=element_blank()) +
  annotate("point", x = MCI_m$age, y = MCI_m$trailDiff, colour = "darkgreen", shape = 15, cex=3) +
  annotate("point", x = AD_m$age, y = AD_m$trailDiff, colour = "purple2", pch=17, shape = 17, cex=3)+
  xlim(20,90)

ggdraw() + 
  draw_plot(plot1, 0, .5, 1, .5) +
  draw_plot(plot2, 0, 0, 0.5, .5) +
  draw_plot(plot3, 0.5, 0, .45, .5)

lm <- lm(trailDiff ~ age*genotype*sex, geno_combined)
summary(lm)

lm_f <- lm(trailDiff ~ age*genotype, combo_f)
summary(lm_f)

lm_m <- lm(trailDiff ~ age*genotype, combo_m)
summary(lm_m)

anova(lm)
anova(lm_f)
anova(lm_m)
```


```{r number-spanforwards, echo = FALSE}

plot1<-ggplot(geno_combined, aes(x = age, y = fwd_total_correct,
                                 color = genotype,  fill = genotype)) + 
  geom_point(aes(shape = Risk)) +
  geom_smooth(formula = y ~ x, method = "lm", alpha = 0.2) +
  labs(title = "Forward Total Correct score linear model",
       subtitle = "Both males and females",
       x = "Age", y = "Forward Total Correct scores") +
  theme_bw() +
  background_grid(major = "xy", minor = "none") +
  annotate("point", x = MCI$age, y = MCI$fwd_total_correct, colour = "darkgreen", shape = 15, cex=3) +
  annotate("point", x = AD$age, y = AD$fwd_total_correct, colour = "purple2", pch=17, shape = 17, cex=3) +
  xlim(20,90)

plot2 <- ggplot(combo_f, aes(age, fwd_total_correct, 
                                   color = genotype, fill = genotype)) + 
  geom_point(aes(shape = Risk)) + 
  stat_smooth(method = "lm", alpha = 0.2) +
  background_grid(major = 'xy', minor = "none") + # add thin horizontal lines 
  panel_border() + 
  theme_bw()+
  labs(x = "Age", y = "Forward Total Correct score", title = "Female") +
  theme(legend.position="none") +
  annotate("point", x = MCI_f$age, y = MCI_f$fwd_total_correct, colour = "darkgreen", shape = 15, cex=3) +
  annotate("point", x = AD_f$age, y = AD_f$fwd_total_correct, colour = "purple2", pch=17, shape = 17, cex=3) +
  xlim(20,90)

plot3 <- ggplot(combo_m, aes(age, fwd_total_correct, 
                                   color = genotype, fill = genotype)) + 
  geom_point(aes(shape = Risk)) + 
  stat_smooth(method = "lm", alpha = 0.2) +
  background_grid(major = 'xy', minor = "none") + # add thin horizontal lines 
  panel_border() + 
  theme_bw()+
  labs(x = "Age", title = "Male") +
  theme(legend.position="none", axis.ticks.y=element_blank(), axis.title.y=element_blank(),
        axis.text.y=element_blank()) +
  annotate("point", x = MCI_m$age, y = MCI_m$fwd_total_correct, colour = "darkgreen", shape = 15, cex=3) +
  annotate("point", x = AD_m$age, y = AD_m$fwd_total_correct, colour = "purple2", pch=17, shape = 17, cex=3) +
  xlim(20,90)


ggdraw() + 
  draw_plot(plot1, 0, .5, 1, .5) +
  draw_plot(plot2, 0, 0, 0.5, .5) +
  draw_plot(plot3, 0.5, 0, .45, .5)

lm <- lm(fwd_total_correct ~ age*genotype*sex, geno_combined)
summary(lm)

lm_f <- lm(fwd_total_correct ~ age*genotype, combo_f)
summary(lm_f)

lm_m <- lm(fwd_total_correct ~ age*genotype, combo_m)
summary(lm_m)

anova(lm)
anova(lm_f)
anova(lm_m)
```


```{r number-spanbackwards, echo = FALSE}

plot1<-ggplot(geno_combined, aes(x = age, y = bckwds_total_correct,
                                 color = genotype,  fill = genotype)) + 
  geom_point(aes(shape = Risk)) +
  geom_smooth(formula = y ~ x, method = "lm", alpha = 0.2) +
  labs(title = "Backward Total Correct score linear model",
       subtitle = "Both males and females",
       x = "Age", y = "Backward Total Correct scores") +
  theme_bw() +
  background_grid(major = "xy", minor = "none") +
  annotate("point", x = MCI$age, y = MCI$bckwds_total_correct, colour = "darkgreen", shape = 15, cex=3) +
  annotate("point", x = AD$age, y = AD$bckwds_total_correct, colour = "purple2", pch=17, shape = 17, cex=3) +
  xlim(20,90)


plot2 <- ggplot(combo_f, aes(age, bckwds_total_correct, 
                                   color = genotype, fill = genotype)) + 
  geom_point(aes(shape = Risk)) + 
  stat_smooth(method = "lm", alpha = 0.2) +
  background_grid(major = 'xy', minor = "none") + # add thin horizontal lines 
  panel_border() + 
  theme_bw()+
  labs(x = "Age", y = "Backward Total Correct score", title = "Female") +
  theme(legend.position="none") +
  annotate("point", x = MCI_f$age, y = MCI_f$bckwds_total_correct, colour = "darkgreen", shape = 15, cex=3) +
  annotate("point", x = AD_f$age, y = AD_f$bckwds_total_correct, colour = "purple2", pch=17, shape = 17, cex=3) +
  xlim(20,90)

plot3 <- ggplot(combo_m, aes(age, bckwds_total_correct, 
                                   color = genotype, fill = genotype)) + 
  geom_point(aes(shape = Risk)) + 
  stat_smooth(method = "lm", alpha = 0.2) +
  background_grid(major = 'xy', minor = "none") + # add thin horizontal lines 
  panel_border() + 
  theme_bw()+
  labs(x = "Age", title = "Male") +
  theme(legend.position="none", axis.ticks.y=element_blank(), axis.title.y=element_blank(),
        axis.text.y=element_blank()) +
  annotate("point", x = MCI_m$age, y = MCI_m$bckwds_total_correct, colour = "darkgreen", shape = 15, cex=3) +
  annotate("point", x = AD_m$age, y = AD_m$bckwds_total_correct, colour = "purple2", pch=17, shape = 17, cex=3) +
  xlim(20,90)

ggdraw() + 
  draw_plot(plot1, 0, .5, 1, .5) +
  draw_plot(plot2, 0, 0, 0.5, .5) +
  draw_plot(plot3, 0.5, 0, .45, .5)

lm <- lm(bckwds_total_correct ~ age*genotype*sex, geno_combined)
summary(lm)

lm_f <- lm(bckwds_total_correct ~ age*genotype, combo_f)
summary(lm_f)

lm_m <- lm(bckwds_total_correct ~ age*genotype, combo_m)
summary(lm_m)

anova(lm)
anova(lm_f)
anova(lm_m)
```


```{r number-spanfwdsmax, echo = FALSE}

plot1<-ggplot(geno_combined, aes(x = age, y = fwd_max_length,
                                 color = genotype,  fill = genotype)) + 
  geom_point(aes(shape = Risk)) +
  geom_smooth(formula = y ~ x, method = "lm", alpha = 0.2) +
  labs(title = "Forward Max Length linear model",
       subtitle = "Both males and females",
       x = "Age", y = "Forward Max Length scores") +
  theme_bw() +
  background_grid(major = "xy", minor = "none")  +
  annotate("point", x = MCI$age, y = MCI$fwd_max_lengt, colour = "darkgreen", shape = 15, cex=3) +
  annotate("point", x = AD$age, y = AD$fwd_max_lengt, colour = "purple2", pch=17, shape = 17, cex=3) +
  xlim(20,90)

plot2 <- ggplot(combo_f, aes(age, fwd_max_length, 
                                   color = genotype, fill = genotype)) + 
  geom_point(aes(shape = Risk)) + 
  stat_smooth(method = "lm", alpha = 0.2) +
  background_grid(major = 'xy', minor = "none") + # add thin horizontal lines 
  panel_border() + 
  theme_bw()+
  labs(x = "Age", y = "Forward max length score", title = "Female") +
  theme(legend.position="none") +
  annotate("point", x = MCI_f$age, y = MCI_f$fwd_max_lengt, colour = "darkgreen", shape = 15, cex=3) +
  annotate("point", x = AD_f$age, y = AD_f$fwd_max_lengt, colour = "purple2", pch=17, shape = 17, cex=3) +
  xlim(20,90)

plot3 <- ggplot(combo_m, aes(age, fwd_max_length, 
                                   color = genotype, fill = genotype)) + 
  geom_point(aes(shape = Risk)) + 
  stat_smooth(method = "lm", alpha = 0.2) +
  background_grid(major = 'xy', minor = "none") + # add thin horizontal lines 
  panel_border() + 
  theme_bw()+
  labs(x = "Age", title = "Male") +
  theme(legend.position="none", axis.ticks.y=element_blank(), axis.title.y=element_blank(),
        axis.text.y=element_blank()) +
  annotate("point", x = MCI_m$age, y = MCI_m$fwd_max_lengt, colour = "darkgreen", shape = 15, cex=3) +
  annotate("point", x = AD_m$age, y = AD_m$fwd_max_lengt, colour = "purple2", pch=17, shape = 17, cex=3) +
  xlim(20,90)

ggdraw() + 
  draw_plot(plot1, 0, .5, 1, .5) +
  draw_plot(plot2, 0, 0, 0.5, .5) +
  draw_plot(plot3, 0.5, 0, .45, .5)


lm <- lm(fwd_max_length ~ age*genotype*sex, geno_combined)
summary(lm)

lm_f <- lm(fwd_max_length ~ age*genotype, combo_f)
summary(lm_f)

lm_m <- lm(fwd_max_length ~ age*genotype, combo_m)
summary(lm_m)

anova(lm)
anova(lm_f)
anova(lm_m)
```


```{r number-spanbckwdsmax, echo = FALSE}

plot1<-ggplot(geno_combined, aes(x = age, y = bckwds_max_length,
                                 color = genotype,  fill = genotype)) + 
  geom_point(aes(shape = Risk)) +
  geom_smooth(formula = y ~ x, method = "lm", alpha = 0.2) +
  labs(title = "Backward Max Length linear model",
       subtitle = "Both males and females",
       x = "Age", y = "Backward Max Length scores") +
  theme_bw() +
  background_grid(major = "xy", minor = "none")  +
  annotate("point", x = MCI$age, y = MCI$bckwds_max_length, colour = "darkgreen", shape = 15, cex=3) +
  annotate("point", x = AD$age, y = AD$bckwds_max_length, colour = "purple2", pch=17, shape = 17, cex=3) +
  xlim(20,90)

plot2 <- ggplot(combo_f, aes(age, bckwds_max_length, 
                                   color = genotype, fill = genotype)) + 
  geom_point(aes(shape = Risk)) + 
  stat_smooth(method = "lm", alpha = 0.2) +
  background_grid(major = 'xy', minor = "none") + # add thin horizontal lines 
  panel_border() + 
  theme_bw()+
  labs(x = "Age", y = "Backwards max length score", title = "Female") +
  theme(legend.position="none") +
  annotate("point", x = MCI_f$age, y = MCI_f$bckwds_max_length, colour = "darkgreen", shape = 15, cex=3) +
  annotate("point", x = AD_f$age, y = AD_f$bckwds_max_length, colour = "purple2", pch=17, shape = 17, cex=3) +
  xlim(20,90)

plot3 <- ggplot(combo_m, aes(age, bckwds_max_length, 
                                   color = genotype, fill = genotype)) + 
  geom_point(aes(shape = Risk)) + 
  stat_smooth(method = "lm", alpha = 0.2) +
  background_grid(major = 'xy', minor = "none") + # add thin horizontal lines 
  panel_border() + 
  theme_bw()+
  labs(x = "Age", title = "Male") +
  theme(legend.position="none", axis.ticks.y=element_blank(), axis.title.y=element_blank(),
        axis.text.y=element_blank()) +
  annotate("point", x = MCI_m$age, y = MCI_m$bckwds_max_length, colour = "darkgreen", shape = 15, cex=3) +
  annotate("point", x = AD_m$age, y = AD_m$bckwds_max_length, colour = "purple2", pch=17, shape = 17, cex=3) +
  xlim(20,90)

ggdraw() + 
  draw_plot(plot1, 0, .5, 1, .5) +
  draw_plot(plot2, 0, 0, 0.5, .5) +
  draw_plot(plot3, 0.5, 0, .45, .5)

lm <- lm(bckwds_max_length ~ age*genotype*sex, geno_combined)
summary(lm)

lm_f <- lm(bckwds_max_length ~ age*genotype, combo_f)
summary(lm_f)

lm_m <- lm(bckwds_max_length ~ age*genotype, combo_m)
summary(lm_m)

anova(lm)
anova(lm_f)
anova(lm_m)
```

```{r ravlt-forg, echo = FALSE}
plot1<-ggplot(geno_combined, aes(x = age, y = RAVLT_FORGETTING,
                          color = genotype,  fill = genotype)) + 
  geom_point(aes(shape = Risk)) +
  geom_smooth(formula = y ~ x, method = "lm", alpha = 0.2) +
  labs(title = "RAVLT forgetting scores linear model",
       subtitle = "Both males and females",
       x = "Age", y = "RAVLT forgetting scores") +
  theme_bw() +
  background_grid(major = "xy", minor = "none") +
  annotate("point", x = MCI$age, y = MCI$RAVLT_FORGETTING, colour = "darkgreen", shape = 15, cex=3) +
  annotate("point", x = AD$age, y = AD$RAVLT_FORGETTING, colour = "purple2", pch=17, shape = 17, cex=3) +
  xlim(20,90)

plot2 <- ggplot(combo_f, aes(age, RAVLT_FORGETTING, 
                                   color = genotype, fill = genotype)) + 
  geom_point(aes(shape = Risk)) + 
  stat_smooth(method = "lm", alpha = 0.2) +
  background_grid(major = 'xy', minor = "none") + # add thin horizontal lines 
  panel_border() + 
  theme_bw()+
  labs(x = "Age", y = "RAVLT forgetting score", title = "Female") +
  theme(legend.position="none") +
  annotate("point", x = MCI_f$age, y = MCI_f$RAVLT_FORGETTING, colour = "darkgreen", shape = 15, cex=3) +
  annotate("point", x = AD_f$age, y = AD_f$RAVLT_FORGETTING, colour = "purple2", pch=17, shape = 17, cex=3) +
  xlim(20,90)

plot3 <- ggplot(combo_m, aes(age, RAVLT_FORGETTING, 
                                   color = genotype, fill = genotype)) + 
  geom_point(aes(shape = Risk)) + 
  stat_smooth(method = "lm", alpha = 0.2) +
  background_grid(major = 'xy', minor = "none") + # add thin horizontal lines 
  panel_border() + 
  theme_bw()+
  labs(x = "Age", title = "Male") +
  theme(legend.position="none", axis.ticks.y=element_blank(), axis.title.y=element_blank(),
        axis.text.y=element_blank()) +
  annotate("point", x = MCI_m$age, y = MCI_m$RAVLT_FORGETTING, colour = "darkgreen", shape = 15, cex=3) +
  annotate("point", x = AD_m$age, y = AD_m$RAVLT_FORGETTING, colour = "purple2", pch=17, shape = 17, cex=3) +
  xlim(20,90)

ggdraw() + 
  draw_plot(plot1, 0, .5, 1, .5) +
  draw_plot(plot2, 0, 0, 0.5, .5) +
  draw_plot(plot3, 0.5, 0, .45, .5)

lm <- lm(RAVLT_FORGETTING ~ age*genotype*sex, geno_combined)
summary(lm)

lm_f <- lm(RAVLT_FORGETTING ~ age*genotype, combo_f)
summary(lm_f)

lm_m <- lm(RAVLT_FORGETTING ~ age*genotype, combo_m)
summary(lm_m)

anova(lm)
anova(lm_f)
anova(lm_m)
```

```{r ravlt-learn, echo = FALSE}

plot1<-ggplot(geno_combined, aes(x = age, y = RAVLT_LEARNING,
                          color = genotype,  fill = genotype)) + 
  geom_point(aes(shape = Risk)) +
  geom_smooth(formula = y ~ x, method = "lm", alpha = 0.2) +
  labs(title = "RAVLT learning scores linear model",
       subtitle = "Both males and females",
       x = "Age", y = "RAVLT learning scores") +
  theme_bw() +
  background_grid(major = "xy", minor = "none") +
  annotate("point", x = MCI$age, y = MCI$RAVLT_LEARNING, colour = "darkgreen", shape = 15, cex=3) +
  annotate("point", x = AD$age, y = AD$RAVLT_LEARNING, colour = "purple2", pch=17, shape = 17, cex=3) +
  xlim(20,90)

plot2 <- ggplot(combo_f, aes(age, RAVLT_LEARNING, 
                                   color = genotype, fill = genotype)) + 
  geom_point(aes(shape = Risk)) + 
  stat_smooth(method = "lm", alpha = 0.2) +
  background_grid(major = 'xy', minor = "none") + # add thin horizontal lines 
  panel_border() + 
  theme_bw()+
  labs(x = "Age", y = "RAVLT learning score", title = "Female") +
  theme(legend.position="none") +
  annotate("point", x = MCI_f$age, y = MCI_f$RAVLT_LEARNING, colour = "darkgreen", shape = 15, cex=3) +
  annotate("point", x = AD_f$age, y = AD_f$RAVLT_LEARNING, colour = "purple2", pch=17, shape = 17, cex=3) +
  xlim(20,90)

plot3 <- ggplot(combo_m, aes(age, RAVLT_LEARNING, 
                                   color = genotype, fill = genotype)) + 
  geom_point(aes(shape = Risk)) + 
  stat_smooth(method = "lm", alpha = 0.2) +
  background_grid(major = 'xy', minor = "none") + # add thin horizontal lines 
  panel_border() + 
  theme_bw()+
  labs(x = "Age", title = "Male") +
  theme(legend.position="none", axis.ticks.y=element_blank(), axis.title.y=element_blank(),
        axis.text.y=element_blank()) +
  annotate("point", x = MCI_m$age, y = MCI_m$RAVLT_LEARNING, colour = "darkgreen", shape = 15, cex=3) +
  annotate("point", x = AD_m$age, y = AD_m$RAVLT_LEARNING, colour = "purple2", pch=17, shape = 17, cex=3) +
  xlim(20,90)

ggdraw() + 
  draw_plot(plot1, 0, .5, 1, .5) +
  draw_plot(plot2, 0, 0, 0.5, .5) +
  draw_plot(plot3, 0.5, 0, .45, .5)

lm <- lm(RAVLT_LEARNING ~ age*genotype*sex, geno_combined)
summary(lm)

lm_f <- lm(RAVLT_LEARNING ~ age*genotype, combo_f)
summary(lm_f)

lravlt_lm_m <- lm(RAVLT_LEARNING ~ age*genotype, combo_m)
summary(lm_m)

anova(lm)
anova(lm_f)
anova(lm_m)
```

```{r ravlt-imm, echo = FALSE}

plot1<-ggplot(geno_combined, aes(x = age, y = RAVLT_IMMEDIATE,
                          color = genotype,  fill = genotype)) + 
  geom_point(aes(shape = Risk)) +
  geom_smooth(formula = y ~ x, method = "lm", alpha = 0.2) +
  labs(title = "RAVLT Immediate scores linear model",
       subtitle = "Both males and females",
       x = "Age", y = "RAVLT Immediate scores") +
  theme_bw() +
  background_grid(major = "xy", minor = "none")  +
  annotate("point", x = MCI$age, y = MCI$RAVLT_IMMEDIATE, colour = "darkgreen", shape = 15, cex=3) +
  annotate("point", x = AD$age, y = AD$RAVLT_IMMEDIATE, colour = "purple2", pch=17, shape = 17, cex=3) +
  xlim(20,90)

plot2 <- ggplot(combo_f, aes(age, RAVLT_IMMEDIATE, 
                                   color = genotype, fill = genotype)) + 
  geom_point(aes(shape = Risk)) + 
  stat_smooth(method = "lm", alpha = 0.2) +
  background_grid(major = 'xy', minor = "none") + # add thin horizontal lines 
  panel_border() + 
  theme_bw()+
  labs(x = "Age", y = "RAVLT immediate score", title = "Female") +
  theme(legend.position="none") +
  annotate("point", x = MCI_f$age, y = MCI_f$RAVLT_IMMEDIATE, colour = "darkgreen", shape = 15, cex=3) +
  annotate("point", x = AD_f$age, y = AD_f$RAVLT_IMMEDIATE, colour = "purple2", pch=17, shape = 17, cex=3) +
  xlim(20,90)

plot3 <- ggplot(combo_m, aes(age, RAVLT_IMMEDIATE, 
                                   color = genotype, fill = genotype)) + 
  geom_point(aes(shape = Risk)) + 
  stat_smooth(method = "lm", alpha = 0.2) +
  background_grid(major = 'xy', minor = "none") + # add thin horizontal lines 
  panel_border() + 
  theme_bw()+
  labs(x = "Age", title = "Male") +
  theme(legend.position="none", axis.ticks.y=element_blank(), axis.title.y=element_blank(),
        axis.text.y=element_blank()) +
  annotate("point", x = MCI_m$age, y = MCI_m$RAVLT_IMMEDIATE, colour = "darkgreen", shape = 15, cex=3) +
  annotate("point", x = AD_m$age, y = AD_m$RAVLT_IMMEDIATE, colour = "purple2", pch=17, shape = 17, cex=3) +
  xlim(20,90)

ggdraw() + 
  draw_plot(plot1, 0, .5, 1, .5) +
  draw_plot(plot2, 0, 0, 0.5, .5) +
  draw_plot(plot3, 0.5, 0, .45, .5)

lm <- lm(RAVLT_IMMEDIATE ~ age*genotype*sex, geno_combined)
summary(lm)

lm_f <- lm(RAVLT_IMMEDIATE ~ age*genotype, combo_f)
summary(lm_f)

imravlt_lm_m <- lm(RAVLT_IMMEDIATE ~ age*genotype, combo_m)
summary(lm_m)

anova(lm)
anova(lm_f)
anova(lm_m)
```

```{r ravlt-7, echo = FALSE}

plot1<-ggplot(geno_combined, aes(x = age, y = AVLT_Trial7,
                          color = genotype,  fill = genotype)) + 
  geom_point(aes(shape = Risk)) +
  geom_smooth(formula = y ~ x, method = "lm", alpha = 0.2) +
  labs(title = "AVLT Trial 7 (delayed) scores linear model",
       subtitle = "Both males and females",
       x = "Age", y = " AVLT Trial 7 scores") +
  theme_bw() +
  background_grid(major = "xy", minor = "none")  +
  annotate("point", x = MCI$age, y = MCI$AVLT_Trial7, colour = "darkgreen", shape = 15, cex=3) +
  annotate("point", x = AD$age, y = AD$AVLT_Trial7, colour = "purple2", pch=17, shape = 17, cex=3) +
  xlim(20,90)

plot2 <- ggplot(combo_f, aes(age, AVLT_Trial7, 
                                   color = genotype, fill = genotype)) + 
  geom_point(aes(shape = Risk)) + 
  stat_smooth(method = "lm", alpha = 0.2) +
  background_grid(major = 'xy', minor = "none") + # add thin horizontal lines 
  panel_border() + 
  theme_bw()+
  labs(x = "Age", y = "AVLT Trial 7 (delayed) score", title = "Female") +
  theme(legend.position="none") +
  annotate("point", x = MCI_f$age, y = MCI_f$AVLT_Trial7, colour = "darkgreen", shape = 15, cex=3) +
  annotate("point", x = AD_f$age, y = AD_f$AVLT_Trial7, colour = "purple2", pch=17, shape = 17, cex=3) +
  xlim(20,90)

plot3 <- ggplot(combo_m, aes(age, AVLT_Trial7, 
                                   color = genotype, fill = genotype)) + 
  geom_point(aes(shape = Risk)) + 
  stat_smooth(method = "lm", alpha = 0.2) +
  background_grid(major = 'xy', minor = "none") + # add thin horizontal lines 
  panel_border() + 
  theme_bw()+
  labs(x = "Age", title = "Male") +
  theme(legend.position="none", axis.ticks.y=element_blank(), axis.title.y=element_blank(),
        axis.text.y=element_blank()) +
  annotate("point", x = MCI_m$age, y = MCI_m$AVLT_Trial7, colour = "darkgreen", shape = 15, cex=3) +
  annotate("point", x = AD_m$age, y = AD_m$AVLT_Trial7, colour = "purple2", pch=17, shape = 17, cex=3) +
  xlim(20,90)

ggdraw() + 
  draw_plot(plot1, 0, .5, 1, .5) +
  draw_plot(plot2, 0, 0, 0.5, .5) +
  draw_plot(plot3, 0.5, 0, .45, .5)

lm <- lm(AVLT_Trial7 ~ age*genotype*sex, geno_combined)
summary(lm)

lm_f <- lm(AVLT_Trial7 ~ age*genotype, combo_f)
summary(lm_f)

lm_m <- lm(AVLT_Trial7 ~ age*genotype, combo_m)
summary(lm_m)

anova(lm)
anova(lm_f)
anova(lm_m)
```

```{r comp-pl, echo = FALSE}
# average of all 12 pleasantness scores
plot1<-ggplot(geno_combined, aes(x = age, y = Composite_Pleasantness,
                          color = genotype,  fill = genotype)) + 
  geom_point(aes(shape = Risk)) +
  geom_smooth(formula = y ~ x, method = "lm", alpha = 0.2) +
  labs(title = "Composite pleasantness scores linear model",
       subtitle = "Both males and females",
       x = "Age", y = "Composite pleasantness score") +
  theme_bw() +
  background_grid(major = "xy", minor = "none")  +
  annotate("point", x = MCI$age, y = MCI$Composite_Pleasantness, colour = "darkgreen", shape = 15, cex=3) +
  annotate("point", x = AD$age, y = AD$Composite_Pleasantness, colour = "purple2", pch=17, shape = 17, cex=3) +
  xlim(20,90)

plot2 <- ggplot(combo_f, aes(age, Composite_Pleasantness, 
                                   color = genotype, fill = genotype)) + 
  geom_point(aes(shape = Risk)) + 
  stat_smooth(method = "lm", alpha = 0.2) +
  background_grid(major = 'xy', minor = "none") + # add thin horizontal lines 
  panel_border() + 
  theme_bw()+
  labs(x = "Age", y = "Composite pleasantness score", title = "Female") +
  theme(legend.position="none") +
  annotate("point", x = MCI_f$age, y = MCI_f$Composite_Pleasantness, colour = "darkgreen", shape = 15, cex=3) +
  annotate("point", x = AD_f$age, y = AD_f$Composite_Pleasantness, colour = "purple2", pch=17, shape = 17, cex=3) +
  xlim(20,90)

plot3 <- ggplot(combo_m, aes(age, Composite_Pleasantness, 
                                   color = genotype, fill = genotype)) + 
  geom_point(aes(shape = Risk)) + 
  stat_smooth(method = "lm", alpha = 0.2) +
  background_grid(major = 'xy', minor = "none") + # add thin horizontal lines 
  panel_border() + 
  theme_bw()+
  labs(x = "Age", title = "Male") +
  theme(legend.position="none", axis.ticks.y=element_blank(), axis.title.y=element_blank(),
        axis.text.y=element_blank()) +
  annotate("point", x = MCI_m$age, y = MCI_m$Composite_Pleasantness, colour = "darkgreen", shape = 15, cex=3) +
  annotate("point", x = AD_m$age, y = AD_m$Composite_Pleasantness, colour = "purple2", pch=17, shape = 17, cex=3) +
  xlim(20,90)

ggdraw() + 
  draw_plot(plot1, 0, .5, 1, .5) +
  draw_plot(plot2, 0, 0, 0.5, .5) +
  draw_plot(plot3, 0.5, 0, .45, .5)

lm <- lm(Composite_Pleasantness ~ age*genotype*sex, geno_combined)
summary(lm)

lm_f <- lm(Composite_Pleasantness ~ age*genotype, combo_f)
summary(lm_f)

lm_m <- lm(Composite_Pleasantness ~ age*genotype, combo_m)
summary(lm_m)

anova(lm)
anova(lm_f)
anova(lm_m)
```

```{r comp-intensity, echo = FALSE}
# average of all 12 intensity scores
plot1<-ggplot(geno_combined, aes(x = age, y = Composite_Intensity,
                          color = genotype,  fill = genotype)) + 
  geom_point(aes(shape = Risk)) +
  geom_smooth(formula = y ~ x, method = "lm", alpha = 0.2) +
  labs(title = "Composite intensity scores linear model",
       subtitle = "Both males and females",
       x = "Age", y = "Composite intensity score") +
  theme_bw() +
  background_grid(major = "xy", minor = "none")  +
  annotate("point", x = MCI$age, y = MCI$Composite_Intensity, colour = "darkgreen", shape = 15, cex=3) +
  annotate("point", x = AD$age, y = AD$Composite_Intensity, colour = "purple2", pch=17, shape = 17, cex=3) +
  xlim(20,90)

plot2 <- ggplot(combo_f, aes(age, Composite_Intensity, 
                                   color = genotype, fill = genotype)) + 
  geom_point(aes(shape = Risk)) + 
  stat_smooth(method = "lm", alpha = 0.2) +
  background_grid(major = 'xy', minor = "none") + # add thin horizontal lines 
  panel_border() + 
  theme_bw()+
  labs(x = "Age", y = "Composite intensity score", title = "Female") +
  theme(legend.position="none") +
  annotate("point", x = MCI_f$age, y = MCI_f$Composite_Intensity, colour = "darkgreen", shape = 15, cex=3) +
  annotate("point", x = AD_f$age, y = AD_f$Composite_Intensity, colour = "purple2", pch=17, shape = 17, cex=3) +
  xlim(20,90)

plot3 <- ggplot(combo_m, aes(age, Composite_Intensity, 
                                   color = genotype, fill = genotype)) + 
  geom_point(aes(shape = Risk)) + 
  stat_smooth(method = "lm", alpha = 0.2) +
  background_grid(major = 'xy', minor = "none") + # add thin horizontal lines 
  panel_border() + 
  theme_bw()+
  labs(x = "Age", title = "Male") +
  theme(legend.position="none", axis.ticks.y=element_blank(), axis.title.y=element_blank(),
        axis.text.y=element_blank()) +
  annotate("point", x = MCI_m$age, y = MCI_m$Composite_Intensity, colour = "darkgreen", shape = 15, cex=3) +
  annotate("point", x = AD_m$age, y = AD_m$Composite_Intensity, colour = "purple2", pch=17, shape = 17, cex=3) +
  xlim(20,90)

ggdraw() + 
  draw_plot(plot1, 0, .5, 1, .5) +
  draw_plot(plot2, 0, 0, 0.5, .5) +
  draw_plot(plot3, 0.5, 0, .45, .5)

lm <- lm(Composite_Intensity ~ age*genotype*sex, geno_combined)
summary(lm)

lm_f <- lm(Composite_Intensity ~ age*genotype, combo_f)
summary(lm_f)

lm_m <- lm(Composite_Intensity ~ age*genotype, combo_m)
summary(lm_m)

anova(lm)
anova(lm_f)
anova(lm_m)
```

```{r comp-fam, echo = FALSE}
# average of all 12 familiarity scores
plot1<-ggplot(geno_combined, aes(x = age, y = Composite_Familiarity,
                          color = genotype,  fill = genotype)) + 
  geom_point(aes(shape = Risk)) +
  geom_smooth(formula = y ~ x, method = "lm", alpha = 0.2) +
  labs(title = "Composite familiarity scores linear model",
       subtitle = "Both males and females",
       x = "Age", y = "Composite familiarity score") +
  theme_bw() +
  background_grid(major = "xy", minor = "none")  +
  annotate("point", x = MCI$age, y = MCI$Composite_Familiarity, colour = "darkgreen", shape = 15, cex=3) +
  annotate("point", x = AD$age, y = AD$Composite_Familiarity, colour = "purple2", pch=17, shape = 17, cex=3) +
  xlim(20,90)

plot2 <- ggplot(combo_f, aes(age, Composite_Familiarity, 
                                   color = genotype, fill = genotype)) + 
  geom_point(aes(shape = Risk)) + 
  stat_smooth(method = "lm", alpha = 0.2) +
  background_grid(major = 'xy', minor = "none") + # add thin horizontal lines 
  panel_border() + 
  theme_bw()+
  labs(x = "Age", y = "Composite familiarity score", title = "Female") +
  theme(legend.position="none") +
  annotate("point", x = MCI_f$age, y = MCI_f$Composite_Familiarity, colour = "darkgreen", shape = 15, cex=3) +
  annotate("point", x = AD_f$age, y = AD_f$Composite_Familiarity, colour = "purple2", pch=17, shape = 17, cex=3) +
  xlim(20,90)

plot3 <- ggplot(combo_m, aes(age, Composite_Familiarity, 
                                   color = genotype, fill = genotype)) + 
  geom_point(aes(shape = Risk)) + 
  stat_smooth(method = "lm", alpha = 0.2) +
  background_grid(major = 'xy', minor = "none") + # add thin horizontal lines 
  panel_border() + 
  theme_bw()+
  labs(x = "Age", title = "Male") +
  theme(legend.position="none", axis.ticks.y=element_blank(), axis.title.y=element_blank(),
        axis.text.y=element_blank()) +
  annotate("point", x = MCI_m$age, y = MCI_m$Composite_Familiarity, colour = "darkgreen", shape = 15, cex=3) +
  annotate("point", x = AD_m$age, y = AD_m$Composite_Familiarity, colour = "purple2", pch=17, shape = 17, cex=3) +
  xlim(20,90)

ggdraw() + 
  draw_plot(plot1, 0, .5, 1, .5) +
  draw_plot(plot2, 0, 0, 0.5, .5) +
  draw_plot(plot3, 0.5, 0, .45, .5)

lm <- lm(Composite_Familiarity ~ age*genotype*sex, geno_combined)
summary(lm)

lm_f <- lm(Composite_Familiarity ~ age*genotype, combo_f)
summary(lm_f)

lm_m <- lm(Composite_Familiarity ~ age*genotype, combo_m)
summary(lm_m)

anova(lm)
anova(lm_f)
anova(lm_m)
```

```{r comp-name, echo = FALSE}
# average of all 12 nameability scores
plot1<-ggplot(geno_combined, aes(x = age, y = Composite_Nameability,
                          color = genotype,  fill = genotype)) + 
  geom_point(aes(shape = Risk)) +
  geom_smooth(formula = y ~ x, method = "lm", alpha = 0.2) +
  labs(title = "Composite nameability scores linear model",
       subtitle = "Both males and females",
       x = "Age", y = "Composite nameability score") +
  theme_bw() +
  background_grid(major = "xy", minor = "none")  +
  annotate("point", x = MCI$age, y = MCI$Composite_Nameability, colour = "darkgreen", shape = 15, cex=3) +
  annotate("point", x = AD$age, y = AD$Composite_Nameability, colour = "purple2", pch=17, shape = 17, cex=3) +
  xlim(20,90)

plot2 <- ggplot(combo_f, aes(age, Composite_Nameability, 
                                   color = genotype, fill = genotype)) + 
  geom_point(aes(shape = Risk)) + 
  stat_smooth(method = "lm", alpha = 0.2) +
  background_grid(major = 'xy', minor = "none") + # add thin horizontal lines 
  panel_border() + 
  theme_bw()+
  labs(x = "Age", y = "Composite nameability score", title = "Female") +
  theme(legend.position="none") +
  annotate("point", x = MCI_f$age, y = MCI_f$Composite_Nameability, colour = "darkgreen", shape = 15, cex=3) +
  annotate("point", x = AD_f$age, y = AD_f$Composite_Nameability, colour = "purple2", pch=17, shape = 17, cex=3) +
  xlim(20,90)

plot3 <- ggplot(combo_m, aes(age, Composite_Nameability, 
                                   color = genotype, fill = genotype)) + 
  geom_point(aes(shape = Risk)) + 
  stat_smooth(method = "lm", alpha = 0.2) +
  background_grid(major = 'xy', minor = "none") + # add thin horizontal lines 
  panel_border() + 
  theme_bw()+
  labs(x = "Age", title = "Male") +
  theme(legend.position="none", axis.ticks.y=element_blank(), axis.title.y=element_blank(),
        axis.text.y=element_blank()) +
  annotate("point", x = MCI_m$age, y = MCI_m$Composite_Nameability, colour = "darkgreen", shape = 15, cex=3) +
  annotate("point", x = AD_m$age, y = AD_m$Composite_Nameability, colour = "purple2", pch=17, shape = 17, cex=3) +
  xlim(20,90)
  

ggdraw() + 
  draw_plot(plot1, 0, .5, 1, .5) +
  draw_plot(plot2, 0, 0, 0.5, .5) +
  draw_plot(plot3, 0.5, 0, .45, .5)

lm <- lm(Composite_Nameability ~ age*genotype*sex, geno_combined)
summary(lm)

lm_f <- lm(Composite_Nameability ~ age*genotype, combo_f)
summary(lm_f)

lm_m <- lm(Composite_Nameability ~ age*genotype, combo_m)
summary(lm_m)

anova(lm)
anova(lm_f)
anova(lm_m)
```

```{r odor-rec, echo = FALSE}
plot1<-ggplot(geno_combined, aes(x = age, y = Recognized,
                          color = genotype,  fill = genotype)) + 
  geom_point(aes(shape = Risk)) +
  geom_smooth(formula = y ~ x, method = "lm", alpha = 0.2) +
  labs(title = "Odor percent correctly recognized linear model",
       subtitle = "Both males and females",
       x = "Age", y = "Odor percent correctly recognized") +
  theme_bw() +
  background_grid(major = "xy", minor = "none")  +
  annotate("point", x = MCI$age, y = MCI$Recognized, colour = "darkgreen", shape = 15, cex=3) +
  annotate("point", x = AD$age, y = AD$Recognized, colour = "purple2", pch=17, shape = 17, cex=3) +
  xlim(20,90)

plot2 <- ggplot(combo_f, aes(age, Recognized, 
                                   color = genotype, fill = genotype)) + 
  geom_point(aes(shape = Risk)) + 
  stat_smooth(method = "lm", alpha = 0.2) +
  background_grid(major = 'xy', minor = "none") + # add thin horizontal lines 
  panel_border() + 
  theme_bw()+
  labs(x = "Age", y = "Percent correctly recognized", title = "Female") +
  theme(legend.position="none") +
  annotate("point", x = MCI_f$age, y = MCI_f$Recognized, colour = "darkgreen", shape = 15, cex=3) +
  annotate("point", x = AD_f$age, y = AD_f$Recognized, colour = "purple2", pch=17, shape = 17, cex=3) +
  xlim(20,90)

plot3 <- ggplot(combo_m, aes(age, Recognized, 
                                   color = genotype, fill = genotype)) + 
  geom_point(aes(shape = Risk)) + 
  stat_smooth(method = "lm", alpha = 0.2) +
  background_grid(major = 'xy', minor = "none") + # add thin horizontal lines 
  panel_border() + 
  theme_bw()+
  labs(x = "Age", title = "Male") +
  theme(legend.position="none", axis.ticks.y=element_blank(), axis.title.y=element_blank(),
        axis.text.y=element_blank()) +
  annotate("point", x = MCI_m$age, y = MCI_m$Recognized, colour = "darkgreen", shape = 15, cex=3) +
  annotate("point", x = AD_m$age, y = AD_m$Recognized, colour = "purple2", pch=17, shape = 17, cex=3) +
  xlim(20,90)
  
 
ggdraw() + 
  draw_plot(plot1, 0, .5, 1, .5) +
  draw_plot(plot2, 0, 0, 0.5, .5) +
  draw_plot(plot3, 0.5, 0, .45, .5)

lm <- lm(Recognized ~ age*genotype*sex, geno_combined)
summary(lm)

lm_f <- lm(Recognized ~ age*genotype, combo_f)
summary(lm_f)

lm_m <- lm(Recognized ~ age*genotype, combo_m)
summary(lm_m)

anova(lm)
anova(lm_f)
anova(lm_m)
```

```{r odor-precent, echo = FALSE}

plot1<-ggplot(geno_combined, aes(x = age, y = PrecentCorrectRecall,
                          color = genotype,  fill = genotype)) + 
  geom_point(aes(shape = Risk)) +
  geom_smooth(formula = y ~ x, method = "lm", alpha = 0.2) +
  labs(title = "Odor recognition percent correct recall linear model",
       subtitle = "Both males and females",
       x = "Age", y = "Odor recognition percent correct recall") +
  theme_bw() +
  background_grid(major = "xy", minor = "none")  +
  annotate("point", x = MCI$age, y = MCI$PrecentCorrectRecall, colour = "darkgreen", shape = 15, cex=3) +
  annotate("point", x = AD$age, y = AD$PrecentCorrectRecall, colour = "purple2", pch=17, shape = 17, cex=3) +
  xlim(20,90)

plot2 <- ggplot(combo_f, aes(age, PrecentCorrectRecall, 
                                   color = genotype, fill = genotype)) + 
  geom_point(aes(shape = Risk)) + 
  stat_smooth(method = "lm", alpha = 0.2) +
  background_grid(major = 'xy', minor = "none") + # add thin horizontal lines 
  panel_border() + 
  theme_bw()+
  labs(x = "Age", y = "Percent correct recall", title = "Female") +
  theme(legend.position="none") +
  annotate("point", x = MCI_f$age, y = MCI_f$PrecentCorrectRecall, colour = "darkgreen", shape = 15, cex=3) +
  annotate("point", x = AD_f$age, y = AD_f$PrecentCorrectRecall, colour = "purple2", pch=17, shape = 17, cex=3) +
  xlim(20,90)

plot3 <- ggplot(combo_m, aes(age, PrecentCorrectRecall, 
                                   color = genotype, fill = genotype)) + 
  geom_point(aes(shape = Risk)) + 
  stat_smooth(method = "lm", alpha = 0.2) +
  background_grid(major = 'xy', minor = "none") + # add thin horizontal lines 
  panel_border() + 
  theme_bw()+
  labs(x = "Age", title = "Male") +
  theme(legend.position="none", axis.ticks.y=element_blank(), axis.title.y=element_blank(),
        axis.text.y=element_blank()) +
  annotate("point", x = MCI_m$age, y = MCI_m$PrecentCorrectRecall, colour = "darkgreen", shape = 15, cex=3) +
  annotate("point", x = AD_m$age, y = AD_m$PrecentCorrectRecall, colour = "purple2", pch=17, shape = 17, cex=3) +
  xlim(20,90)

ggdraw() + 
  draw_plot(plot1, 0, .5, 1, .5) +
  draw_plot(plot2, 0, 0, 0.5, .5) +
  draw_plot(plot3, 0.5, 0, .45, .5)

lm <- lm(PrecentCorrectRecall ~ age*genotype*sex, geno_combined)
summary(lm)

lm_f <- lm(PrecentCorrectRecall ~ age*genotype, combo_f)
summary(lm_f)

lm_m <- lm(PrecentCorrectRecall ~ age*genotype, combo_m)
summary(lm_m)

anova(lm)
anova(lm_f)
anova(lm_m)
```

```{r delay-benson, echo = FALSE}

plot1<-ggplot(geno_combined, aes(x = age, y = Delay_BensonTotal,
                          color = genotype,  fill = genotype)) + 
  geom_point(aes(shape = Risk)) +
  geom_smooth(formula = y ~ x, method = "lm", alpha = 0.2) +
  labs(title = "Total delayed Benson scores linear model",
       subtitle = "Both males and females",
       x = "Age", y = "Total delayed Benson  score") +
  theme_bw() +
  background_grid(major = "xy", minor = "none") +
  annotate("point", x = MCI$age, y = MCI$Delay_BensonTotal, colour = "darkgreen", shape = 15, cex=3) +
  annotate("point", x = AD$age, y = AD$Delay_BensonTotal, colour = "purple2", pch=17, shape = 17, cex=3) +
  xlim(20,90)


plot2 <- ggplot(combo_f, aes(age, Delay_BensonTotal, 
                                   color = genotype, fill = genotype)) + 
  geom_point(aes(shape = Risk)) + 
  stat_smooth(method = "lm", alpha = 0.2) +
  background_grid(major = 'xy', minor = "none") + # add thin horizontal lines 
  panel_border() + 
  theme_bw()+
  labs(x = "Age", y = "Total delayed Benson scores", title = "Female") +
  theme(legend.position="none") +
  annotate("point", x = MCI_f$age, y = MCI_f$Delay_BensonTotal, colour = "darkgreen", shape = 15, cex=3) +
  annotate("point", x = AD_f$age, y = AD_f$Delay_BensonTotal, colour = "purple2", pch=17, shape = 17, cex=3) +
  xlim(20,90)

plot3 <- ggplot(combo_m, aes(age, Delay_BensonTotal, 
                                   color = genotype, fill = genotype)) + 
  geom_point(aes(shape = Risk)) + 
  stat_smooth(method = "lm", alpha = 0.2) +
  background_grid(major = 'xy', minor = "none") + # add thin horizontal lines 
  panel_border() + 
  theme_bw()+
  labs(x = "Age", title = "Male") +
  theme(legend.position="none", axis.ticks.y=element_blank(), axis.title.y=element_blank(),
        axis.text.y=element_blank()) +
  annotate("point", x = MCI_m$age, y = MCI_m$Delay_BensonTotal, colour = "darkgreen", shape = 15, cex=3) +
  annotate("point", x = AD_m$age, y = AD_m$Delay_BensonTotal, colour = "purple2", pch=17, shape = 17, cex=3) +
  xlim(20,90)

ggdraw() + 
  draw_plot(plot1, 0, .5, 1, .5) +
  draw_plot(plot2, 0, 0, 0.5, .5) +
  draw_plot(plot3, 0.5, 0, .45, .5)

lm <- lm(Delay_BensonTotal ~ age*genotype*sex, geno_combined)
summary(lm)

lm_f <- lm(Delay_BensonTotal ~ age*genotype, combo_f)
summary(lm_f)

lm_m <- lm(Delay_BensonTotal ~ age*genotype, combo_m)
summary(lm_m)

anova(lm)
anova(lm_f)
anova(lm_m)
```

```{r imm-benson, echo = FALSE}

plot1<-ggplot(geno_combined, aes(x = age, y = Im_BensonTotal,
                          color = genotype,  fill = genotype)) + 
  geom_point(aes(shape = Risk)) +
  geom_smooth(formula = y ~ x, method = "lm", alpha = 0.2) +
  labs(title = "Total immediate Benson scores linear model",
       subtitle = "Both males and females",
       x = "Age", y = "Total immediate Benson  score") +
  theme_bw() +
  background_grid(major = "xy", minor = "none") +
  annotate("point", x = MCI$age, y = MCI$Im_BensonTotal, colour = "darkgreen", shape = 15, cex=3) +
  annotate("point", x = AD$age, y = AD$Im_BensonTotal, colour = "purple2", pch=17, shape = 17, cex=3) +
  xlim(20,90)

plot2 <- ggplot(combo_f, aes(age, Im_BensonTotal, 
                                   color = genotype, fill = genotype)) + 
  geom_point(aes(shape = Risk)) + 
  stat_smooth(method = "lm", alpha = 0.2) +
  background_grid(major = 'xy', minor = "none") + # add thin horizontal lines 
  panel_border() + 
  theme_bw()+
  labs(x = "Age", y = "Immediate delayed Benson scores", title = "Female") +
  theme(legend.position="none") +
  annotate("point", x = MCI_f$age, y = MCI_f$Im_BensonTotal, colour = "darkgreen", shape = 15, cex=3) +
  annotate("point", x = AD_f$age, y = AD_f$Im_BensonTotal, colour = "purple2", pch=17, shape = 17, cex=3) +
  xlim(20,90)

plot3 <- ggplot(combo_m, aes(age, Im_BensonTotal, 
                                   color = genotype, fill = genotype)) + 
  geom_point(aes(shape = Risk)) + 
  stat_smooth(method = "lm", alpha = 0.2) +
  background_grid(major = 'xy', minor = "none") + # add thin horizontal lines 
  panel_border() + 
  theme_bw()+
  labs(x = "Age", title = "Male") +
  theme(legend.position="none", axis.ticks.y=element_blank(), axis.title.y=element_blank(),
        axis.text.y=element_blank()) +
  annotate("point", x = MCI_m$age, y = MCI_m$Im_BensonTotal, colour = "darkgreen", shape = 15, cex=3) +
  annotate("point", x = AD_m$age, y = AD_m$Im_BensonTotal, colour = "purple2", pch=17, shape = 17, cex=3) +
  xlim(20,90)

ggdraw() + 
  draw_plot(plot1, 0, .5, 1, .5) +
  draw_plot(plot2, 0, 0, 0.5, .5) +
  draw_plot(plot3, 0.5, 0, .45, .5)

lm <- lm(Im_BensonTotal ~ age*genotype*sex, geno_combined)
summary(lm)

lm_f <- lm(Im_BensonTotal ~ age*genotype, combo_f)
summary(lm_f)

lm_m <- lm(Im_BensonTotal ~ age*genotype, combo_m)
summary(lm_m)

anova(lm)
anova(lm_f)
anova(lm_m)
```

```{r story-delay, echo = FALSE}

plot1<-ggplot(geno_combined, aes(x = age, y = Delayed_verbatim,
                          color = genotype,  fill = genotype)) + 
  geom_point(aes(shape = Risk)) +
  geom_smooth(formula = y ~ x, method = "lm", alpha = 0.2) +
  labs(title = "Story delayed verbatim scores linear model",
       subtitle = "Both males and females",
       x = "Age", y = "Story delayed verbatim score") +
  theme_bw() +
  background_grid(major = "xy", minor = "none")  +
  annotate("point", x = MCI$age, y = MCI$Delayed_verbatim, colour = "darkgreen", shape = 15, cex=3) +
  annotate("point", x = AD$age, y = AD$Delayed_verbatim, colour = "purple2", pch=17, shape = 17, cex=3) +
  xlim(20,90)

plot2 <- ggplot(combo_f, aes(age, Delayed_verbatim, 
                                   color = genotype, fill = genotype)) + 
  geom_point(aes(shape = Risk)) + 
  stat_smooth(method = "lm", alpha = 0.2) +
  background_grid(major = 'xy', minor = "none") + # add thin horizontal lines 
  panel_border() + 
  theme_bw()+
  labs(x = "Age", y = "Story delayed verbatim scores", title = "Female") +
  theme(legend.position="none") +
  annotate("point", x = MCI_f$age, y = MCI_f$Delayed_verbatim, colour = "darkgreen", shape = 15, cex=3) +
  annotate("point", x = AD_f$age, y = AD_f$Delayed_verbatim, colour = "purple2", pch=17, shape = 17, cex=3) +
  xlim(20,90)

plot3 <- ggplot(combo_m, aes(age, Delayed_verbatim, 
                                   color = genotype, fill = genotype)) + 
  geom_point(aes(shape = Risk)) + 
  stat_smooth(method = "lm", alpha = 0.2) +
  background_grid(major = 'xy', minor = "none") + # add thin horizontal lines 
  panel_border() + 
  theme_bw()+
  labs(x = "Age", title = "Male") +
  theme(legend.position="none", axis.ticks.y=element_blank(), axis.title.y=element_blank(),
        axis.text.y=element_blank()) +
  annotate("point", x = MCI_m$age, y = MCI_m$Delayed_verbatim, colour = "darkgreen", shape = 15, cex=3) +
  annotate("point", x = AD_m$age, y = AD_m$Delayed_verbatim, colour = "purple2", pch=17, shape = 17, cex=3) +
  xlim(20,90)

ggdraw() + 
  draw_plot(plot1, 0, .5, 1, .5) +
  draw_plot(plot2, 0, 0, 0.5, .5) +
  draw_plot(plot3, 0.5, 0, .45, .5)

lm <- lm(Delayed_verbatim ~ age*genotype*sex, geno_combined)
summary(lm)

lm_f <- lm(Delayed_verbatim ~ age*genotype, combo_f)
summary(lm_f)

lm_m <- lm(Delayed_verbatim ~ age*genotype, combo_m)
summary(lm_m)

anova(lm)
anova(lm_f)
anova(lm_m)
```

```{r story-imm, echo = FALSE}

plot1<-ggplot(geno_combined, aes(x = age, y = Immediate_verbatim,
                          color = genotype,  fill = genotype)) + 
  geom_point(aes(shape = Risk)) +
  geom_smooth(formula = y ~ x, method = "lm", alpha = 0.2) +
  labs(title = "Story immediate verbatim scores linear model",
       subtitle = "Both males and females",
       x = "Age", y = "Story immediate verbatim score") +
  theme_bw() +
  background_grid(major = "xy", minor = "none") +
  annotate("point", x = MCI$age, y = MCI$Immediate_verbatim, colour = "darkgreen", shape = 15, cex=3) +
  annotate("point", x = AD$age, y = AD$Immediate_verbatim, colour = "purple2", pch=17, shape = 17, cex=3) +
  xlim(20,90)

plot2 <- ggplot(combo_f, aes(age, Immediate_verbatim, 
                                   color = genotype, fill = genotype)) + 
  geom_point(aes(shape = Risk)) + 
  stat_smooth(method = "lm", alpha = 0.2) +
  background_grid(major = 'xy', minor = "none") + # add thin horizontal lines 
  panel_border() + 
  theme_bw()+
  labs(x = "Age", y = "Story immediate verbatim scores", title = "Female") +
  theme(legend.position="none") +
  annotate("point", x = MCI_f$age, y = MCI_f$Immediate_verbatim, colour = "darkgreen", shape = 15, cex=3) +
  annotate("point", x = AD_f$age, y = AD_f$Immediate_verbatim, colour = "purple2", pch=17, shape = 17, cex=3) +
  xlim(20,90)

plot3 <- ggplot(combo_m, aes(age, Immediate_verbatim, 
                                   color = genotype, fill = genotype)) + 
  geom_point(aes(shape = Risk)) + 
  stat_smooth(method = "lm", alpha = 0.2) +
  background_grid(major = 'xy', minor = "none") + # add thin horizontal lines 
  panel_border() + 
  theme_bw()+
  labs(x = "Age", title = "Male") +
  theme(legend.position="none", axis.ticks.y=element_blank(), axis.title.y=element_blank(),
        axis.text.y=element_blank()) +
  annotate("point", x = MCI_m$age, y = MCI_m$Immediate_verbatim, colour = "darkgreen", shape = 15, cex=3) +
  annotate("point", x = AD_m$age, y = AD_m$Immediate_verbatim, colour = "purple2", pch=17, shape = 17, cex=3) +
  xlim(20,90)

ggdraw() + 
  draw_plot(plot1, 0, .5, 1, .5) +
  draw_plot(plot2, 0, 0, 0.5, .5) +
  draw_plot(plot3, 0.5, 0, .45, .5)


lm <- lm(Immediate_verbatim ~ age*genotype*sex, geno_combined)
summary(lm)

lm_f <- lm(Immediate_verbatim ~ age*genotype, combo_f)
summary(lm_f)

lm_m <- lm(Immediate_verbatim ~ age*genotype, combo_m)
summary(lm_m)

anova(lm)
anova(lm_f)
anova(lm_m)
```

```{r moca-attn, echo = FALSE}

plot1<-ggplot(geno_combined, aes(x = age, y = MOCA_Attention_Digits,
                          color = genotype,  fill = genotype)) + 
    geom_point(aes(shape = Risk)) +
  geom_smooth(formula = y ~ x, method = "lm", alpha = 0.2) +
  labs(title = "Story immediate verbatim scores linear model",
       subtitle = "Both males and females",
       x = "Age", y = "Story immediate verbatim score") +
  theme_bw() +
  background_grid(major = "xy", minor = "none") +
  annotate("point", x = MCI$age, y = MCI$MOCA_Attention_Digits, colour = "darkgreen", shape = 15, cex=3) +
  annotate("point", x = AD$age, y = AD$MOCA_Attention_Digits, colour = "purple2", pch=17, shape = 17, cex=3) +
  xlim(20,90)
  

plot2 <- ggplot(combo_f, aes(age, MOCA_Attention_Digits, 
                                   color = genotype, fill = genotype)) + 
  geom_point(aes(shape = Risk)) + 
  stat_smooth(method = "lm", alpha = 0.2) +
  background_grid(major = 'xy', minor = "none") + # add thin horizontal lines 
  panel_border() + 
  theme_bw()+
  labs(x = "Age", y = "Story immediate verbatim scores", title = "Female") +
  theme(legend.position="none") +
  annotate("point", x = MCI_f$age, y = MCI_f$MOCA_Attention_Digits, colour = "darkgreen", shape = 15, cex=3) +
  annotate("point", x = AD_f$age, y = AD_f$MOCA_Attention_Digits, colour = "purple2", pch=17, shape = 17, cex=3) +
  xlim(20,90)

plot3 <- ggplot(combo_m, aes(age, MOCA_Attention_Digits, 
                                   color = genotype, fill = genotype)) + 
  geom_point(aes(shape = Risk)) + 
  stat_smooth(method = "lm", alpha = 0.2) +
  background_grid(major = 'xy', minor = "none") + # add thin horizontal lines 
  panel_border() + 
  theme_bw()+
  labs(x = "Age", y = "Story immediate verbatim scores", title = "Female") +
  theme(legend.position="none") +
  annotate("point", x = MCI_m$age, y = MCI_m$MOCA_Attention_Digits, colour = "darkgreen", shape = 15, cex=3) +
  annotate("point", x = AD_m$age, y = AD_m$MOCA_Attention_Digits, colour = "purple2", pch=17, shape = 17, cex=3) +
  xlim(20,90)

ggdraw() + 
  draw_plot(plot1, 0, .5, 1, .5) +
  draw_plot(plot2, 0, 0, 0.5, .5) +
  draw_plot(plot3, 0.5, 0, .45, .5)


lm <- lm(MOCA_Attention_Digits ~ age*genotype*sex, geno_combined)
summary(lm)

lm_f <- lm(MOCA_Attention_Digits ~ age*genotype, combo_f)
summary(lm_f)

lm_m <- lm(MOCA_Attention_Digits ~ age*genotype, combo_m)
summary(lm_m)

anova(lm)
anova(lm_f)
anova(lm_m)
```

```{r moca-mem, echo = FALSE}

plot1<-ggplot(geno_combined, aes(x = age, y = MOCA_Memory,
                          color = genotype,  fill = genotype)) + 
    geom_point(aes(shape = Risk)) +
  geom_smooth(formula = y ~ x, method = "lm", alpha = 0.2) +
  labs(title = "MOCA Memory scores linear model",
       subtitle = "Both males and females",
       x = "Age", y = "MOCA_Memory") +
  theme_bw() +
  background_grid(major = "xy", minor = "none") +
  annotate("point", x = MCI$age, y = MCI$MOCA_Memory, colour = "darkgreen", shape = 15, cex=3) +
  annotate("point", x = AD$age, y = AD$MOCA_Memory, colour = "purple2", pch=17, shape = 17, cex=3) +
  xlim(20,90)
  

plot2 <- ggplot(combo_f, aes(age, MOCA_Memory, 
                                   color = genotype, fill = genotype)) + 
  geom_point(aes(shape = Risk)) + 
  stat_smooth(method = "lm", alpha = 0.2) +
  background_grid(major = 'xy', minor = "none") + # add thin horizontal lines 
  panel_border() + 
  theme_bw()+
  labs(x = "Age", y = "MOCA_Memory", title = "Female") +
  theme(legend.position="none") +
  annotate("point", x = MCI_f$age, y = MCI_f$MOCA_Memory, colour = "darkgreen", shape = 15, cex=3) +
  annotate("point", x = AD_f$age, y = AD_f$MOCA_Memory, colour = "purple2", pch=17, shape = 17, cex=3) +
  xlim(20,90)

plot3 <- ggplot(combo_m, aes(age, MOCA_Memory, 
                                   color = genotype, fill = genotype)) + 
  geom_point(aes(shape = Risk)) + 
  stat_smooth(method = "lm", alpha = 0.2) +
  background_grid(major = 'xy', minor = "none") + # add thin horizontal lines 
  panel_border() + 
  theme_bw()+
  labs(x = "Age", y = "MOCA_Memory", title = "Female") +
  theme(legend.position="none") +
  annotate("point", x = MCI_m$age, y = MCI_m$MOCA_Memory, colour = "darkgreen", shape = 15, cex=3) +
  annotate("point", x = AD_m$age, y = AD_m$MOCA_Memory, colour = "purple2", pch=17, shape = 17, cex=3) +
  xlim(20,90)

ggdraw() + 
  draw_plot(plot1, 0, .5, 1, .5) +
  draw_plot(plot2, 0, 0, 0.5, .5) +
  draw_plot(plot3, 0.5, 0, .45, .5) 

lm <- lm(MOCA_Memory ~ age*genotype*sex, geno_combined)
summary(lm)

lm_f <- lm(MOCA_Memory ~ age*genotype, combo_f)
summary(lm_f)

lm_m <- lm(MOCA_Memory ~ age*genotype, combo_m)
summary(lm_m)

anova(lm)
anova(lm_f)
anova(lm_m)
```

```{r moca-name, echo = FALSE}

plot1<-ggplot(geno_combined, aes(x = age, y = MOCA_Naming,
                          color = genotype,  fill = genotype)) + 
    geom_point(aes(shape = Risk)) +
  geom_smooth(formula = y ~ x, method = "lm", alpha = 0.2) +
  labs(title = "MOCA Naming scores linear model",
       subtitle = "Both males and females",
       x = "Age", y = "MOCA Naming Score") +
  theme_bw() +
  background_grid(major = "xy", minor = "none") +
  annotate("point", x = MCI$age, y = MCI$MOCA_Naming, colour = "darkgreen", shape = 15, cex=3) +
  annotate("point", x = AD$age, y = AD$MOCA_Naming, colour = "purple2", pch=17, shape = 17, cex=3) +
  xlim(20,90)
  

plot2 <- ggplot(combo_f, aes(age, MOCA_Naming, 
                                   color = genotype, fill = genotype)) + 
  geom_point(aes(shape = Risk)) + 
  stat_smooth(method = "lm", alpha = 0.2) +
  background_grid(major = 'xy', minor = "none") + # add thin horizontal lines 
  panel_border() + 
  theme_bw()+
  labs(x = "Age", y = "MOCA Naming Score", title = "Female") +
  theme(legend.position="none") +
  annotate("point", x = MCI_f$age, y = MCI_f$MOCA_Naming, colour = "darkgreen", shape = 15, cex=3) +
  annotate("point", x = AD_f$age, y = AD_f$MOCA_Naming, colour = "purple2", pch=17, shape = 17, cex=3) +
  xlim(20,90)

plot3 <- ggplot(combo_m, aes(age, MOCA_Naming, 
                                   color = genotype, fill = genotype)) + 
  geom_point(aes(shape = Risk)) + 
  stat_smooth(method = "lm", alpha = 0.2) +
  background_grid(major = 'xy', minor = "none") + # add thin horizontal lines 
  panel_border() + 
  theme_bw()+
  labs(x = "Age", y = "MOCA Naming Score", title = "Female") +
  theme(legend.position="none") +
  annotate("point", x = MCI_m$age, y = MCI_m$MOCA_Naming, colour = "darkgreen", shape = 15, cex=3) +
  annotate("point", x = AD_m$age, y = AD_m$MOCA_Naming, colour = "purple2", pch=17, shape = 17, cex=3) +
  xlim(20,90)

ggdraw() + 
  draw_plot(plot1, 0, .5, 1, .5) +
  draw_plot(plot2, 0, 0, 0.5, .5) +
  draw_plot(plot3, 0.5, 0, .45, .5) 

lm <- lm(MOCA_Naming ~ age*genotype*sex, geno_combined)
summary(lm)

lm_f <- lm(MOCA_Naming ~ age*genotype, combo_f)
summary(lm_f)

lm_m <- lm(MOCA_Naming ~ age*genotype, combo_m)
summary(lm_m)

anova(lm)
anova(lm_f)
anova(lm_m)
```

```{r moca-vis, echo = FALSE}

plot1<-ggplot(geno_combined, aes(x = age, y = MOCA_Visuospatial,
                          color = genotype,  fill = genotype)) + 
    geom_point(aes(shape = Risk)) +
  geom_smooth(formula = y ~ x, method = "lm", alpha = 0.2) +
  labs(title = "MOCA Visuospatial scores linear model",
       subtitle = "Both males and females",
       x = "Age", y = "MOCA Visuospatial Score") +
  theme_bw() +
  background_grid(major = "xy", minor = "none") +
  annotate("point", x = MCI$age, y = MCI$MOCA_Visuospatial, colour = "darkgreen", shape = 15, cex=3) +
  annotate("point", x = AD$age, y = AD$MOCA_Visuospatial, colour = "purple2", pch=17, shape = 17, cex=3) +
  xlim(20,90)
  

plot2 <- ggplot(combo_f, aes(age, MOCA_Visuospatial, 
                                   color = genotype, fill = genotype)) + 
  geom_point(aes(shape = Risk)) + 
  stat_smooth(method = "lm", alpha = 0.2) +
  background_grid(major = 'xy', minor = "none") + # add thin horizontal lines 
  panel_border() + 
  theme_bw()+
  labs(x = "Age", y = "MOCA Visuospatial Score", title = "Female") +
  theme(legend.position="none") +
  annotate("point", x = MCI_f$age, y = MCI_f$MOCA_Visuospatial, colour = "darkgreen", shape = 15, cex=3) +
  annotate("point", x = AD_f$age, y = AD_f$MOCA_Visuospatial, colour = "purple2", pch=17, shape = 17, cex=3) +
  xlim(20,90)

plot3 <- ggplot(combo_m, aes(age, MOCA_Visuospatial, 
                                   color = genotype, fill = genotype)) + 
  geom_point(aes(shape = Risk)) + 
  stat_smooth(method = "lm", alpha = 0.2) +
  background_grid(major = 'xy', minor = "none") + # add thin horizontal lines 
  panel_border() + 
  theme_bw()+
  labs(x = "Age", y = "MOCA Visuospatial Score", title = "Female") +
  theme(legend.position="none") +
  annotate("point", x = MCI_m$age, y = MCI_m$MOCA_Visuospatial, colour = "darkgreen", shape = 15, cex=3) +
  annotate("point", x = AD_m$age, y = AD_m$MOCA_Visuospatial, colour = "purple2", pch=17, shape = 17, cex=3) +
  xlim(20,90)


ggdraw() + 
  draw_plot(plot1, 0, .5, 1, .5) +
  draw_plot(plot2, 0, 0, 0.5, .5) +
  draw_plot(plot3, 0.5, 0, .45, .5) 

lm <- lm(MOCA_Visuospatial ~ age*genotype*sex, geno_combined)
summary(lm)

lm_f <- lm(MOCA_Visuospatial ~ age*genotype, combo_f)
summary(lm_f)

lm_m <- lm(MOCA_Visuospatial ~ age*genotype, combo_m)
summary(lm_m)

anova(lm)
anova(lm_f)
anova(lm_m)
```

```{r moca-total, echo = FALSE}

plot1<-ggplot(geno_combined, aes(x = age, y = MOCA_TOTAL,
                          color = genotype,  fill = genotype)) + 
    geom_point(aes(shape = Risk)) +
  geom_smooth(formula = y ~ x, method = "lm", alpha = 0.2) +
  labs(title = "MOCA Total scores linear model",
       subtitle = "Both males and females",
       x = "Age", y = "MOCA Total Score") +
  theme_bw() +
  background_grid(major = "xy", minor = "none") +
  annotate("point", x = MCI$age, y = MCI$MOCA_TOTAL, colour = "darkgreen", shape = 15, cex=3) +
  annotate("point", x = AD$age, y = AD$MOCA_TOTAL, colour = "purple2", pch=17, shape = 17, cex=3) +
  xlim(20,90)
  

plot2 <- ggplot(combo_f, aes(age, MOCA_TOTAL, 
                                   color = genotype, fill = genotype)) + 
  geom_point(aes(shape = Risk)) + 
  stat_smooth(method = "lm", alpha = 0.2) +
  background_grid(major = 'xy', minor = "none") + # add thin horizontal lines 
  panel_border() + 
  theme_bw()+
  labs(x = "Age", y = "MOCA Total Score", title = "Female") +
  theme(legend.position="none") +
  annotate("point", x = MCI_f$age, y = MCI_f$MOCA_TOTAL, colour = "darkgreen", shape = 15, cex=3) +
  annotate("point", x = AD_f$age, y = AD_f$MOCA_TOTAL, colour = "purple2", pch=17, shape = 17, cex=3) +
  xlim(20,90)

plot3 <- ggplot(combo_m, aes(age, MOCA_TOTAL, 
                                   color = genotype, fill = genotype)) + 
  geom_point(aes(shape = Risk)) + 
  stat_smooth(method = "lm", alpha = 0.2) +
  background_grid(major = 'xy', minor = "none") + # add thin horizontal lines 
  panel_border() + 
  theme_bw()+
  labs(x = "Age", y = "MOCA Total Score", title = "Female") +
  theme(legend.position="none") +
  annotate("point", x = MCI_m$age, y = MCI_m$MOCA_TOTAL, colour = "darkgreen", shape = 15, cex=3) +
  annotate("point", x = AD_m$age, y = AD_m$MOCA_TOTAL, colour = "purple2", pch=17, shape = 17, cex=3) +
  xlim(20,90)


ggdraw() + 
  draw_plot(plot1, 0, .5, 1, .5) +
  draw_plot(plot2, 0, 0, 0.5, .5) +
  draw_plot(plot3, 0.5, 0, .45, .5) 


lm <- lm(MOCA_TOTAL ~ age*genotype*sex, geno_combined)
summary(lm)

lm_f <- lm(MOCA_TOTAL ~ age*genotype, combo_f)
summary(lm_f)

lm_m <- lm(MOCA_TOTAL ~ age*genotype, combo_m)
summary(lm_m)

anova(lm)
anova(lm_f)
anova(lm_m)
```
